### ISSUE TITLE
Confirmations cannot be confirmed

### ISSUE THREAD

**Issue by zudsniper** [Gobot1234/steam.py#260]
### Summary

Mobile Confirmations Broken due to Steam API structural change that adds more detail to the MobileConf struct.

### Reproduction Steps

Here is an example "bot" using the library that demonstrates the failure.  
> **More information is available at [my gist about the issue](https://gist.github.com/zudsniper/69f6494d2741c941e13f050dd8e013c7)**.

<details><summary>🤖<code>steampytest.py source code</code></summary>

<br />  

```py
#!/usr/bin/python3
# 
# warning: MUST be python 3.10 or greater. 
# the environment also is not set up correctly by default. 
# please see `bob_builder.sh` for that

import steam
import os 
import asyncio
from dotenv import load_dotenv

# load environment vars from .env file
load_dotenv()

# allow override via local env vars
# TODO: implement

mainusername = os.getenv('USERNAME')
mainpassword = os.getenv('PASSWORD')
mainshared_secret = os.getenv('SHARED_SECRET')
mainidentity_secret = os.getenv('IDENTITY_SECRET')

class MainBot(steam.Client):
    async def on_ready(self) -> None:
        print("Logged into main bot: ", self.user)

    async def on_trade_receive(self, trade: steam.TradeOffer) -> None:


        print(f"Accepting trade #{trade.id} from {str(trade.partner.id64)}")
        await trade.accept() 
async def main():
    global Main
    Main = MainBot()
    await Main.login(mainusername, mainpassword, shared_secret=mainshared_secret,
             identity_secret=mainidentity_secret)


if name == "main":
    try:
        asyncio.run(main())
    except:
        traceback.print_exc()
```

> 🟡 **Make sure to install dependencies and use python3.10 or greater.** See autoinstaller bash script in [gist](https://gist.github.com/zudsniper/69f6494d2741c941e13f050dd8e013c7).

</details>
  
## Reproduce Problem
1. Start `bot` with `python3 steampytest.py &2>1`  

> _or just open another Terminal and you don't need to run this task in the background_  
  
2. **Using a different account** send a trade to `bot` **that will require a mobile confirmation on `bot`'s end.**  

### Expected Results

Trade to be mobile confirmed successfully from `bot` and trade to go through.

### Actual Results

Script times out while the trade expires. 

### System Information

```
python version: 3.11.4
steam.py version: 1.0.0a2772+g9e897ea
aiohttp version: 3.8.4
betterproto version: 2.0.0b6
operating system info: macOS-10.15.7-x86_64-i386-64bit
```

### Other Tested Environments  
- `Ubuntu-22.04` `WSL2` on `Win10`
- `Debian 11.6`
- `Windows 10` 

### Checklist

- [X] I have searched the issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my username, password, shared/identity secrets and refresh/access tokens from display, if visible.
